source "https://rubygems.org"

ruby "3.4.3"

gem "rails", "~> 7.1.6"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.5"
end

gem 'pry'

gem "devise", "~> 5.0"
gem "devise-jwt", "~> 0.13.0"
gem "pundit", "~> 2.5"
gem "trailblazer", "~> 2.1"
gem "dotenv-rails", "~> 3.2"
gem "responders", "~> 3.2"
gem "trailblazer-rails", "~> 2.4"
